FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN rm -f .env

RUN npx prisma generate

RUN npm run build

EXPOSE 5000

CMD sh -c "sleep 5 && npx prisma db push --accept-data-loss && npx prisma db seed && npm start"